GET http://localhost:5000/users

###
GET http://localhost:5000/users/65599f16371740de9752521f

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "uid": "1217050101",
    "email": "rehan@yahoo.com",
    "displayName": "rehan",
    "firstName": "rehan",
    "lastName": "rehan"
}

###
PATCH http://localhost:5000/user/65599f16371740de9752521f
Content-Type: application/json

{
    "name": "john venom",
    "username": "johnjon",
    "email": "iah@gmail.com",
    "password": "asepheheh"
}

###
DELETE http://localhost:5000/user/655c47298b0cd0dc36248757








############ INCOME ############
###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes

###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/655c616a4f2c4286d1f03593

###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/year/2020

###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/month/2022/11

###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/period/2020-01-01/2022-12-01

###
GET  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/655c58d2aa655821d69429a5

###
PUT  http://localhost:5000/user/655c56f0f9d97a93f8244a00/incomes/655c58d2aa655821d69429a5
Content-Type: application/json

{
    "amount": 5000,
    "category": "Salary",
    "date": "2023-11-01",
    "note": "Monthly salary"
}